<a href="https://colab.research.google.com/github/anwishn/HoPy/blob/main/ch7_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이썬으로 배우는 딥러닝 교과서 ch 7

# ch7. Numpy


---



## 7.1 Numpy 개요

### 7.1.1 Numpy가 하는 일

**Numpy(넘파이)**: 파이썬으로 벡터나 행렬 계산을 빠르게 하도록 특화된 기본 라이브러리

## 7.2 Numpy 1차원 배열

### 7.2.1 import 

import numpy -> 'numpy.모듈명' 형태로 사용

'numpy.모듈명' 대신 'np.모듈명' 형태로 간단하게 사용 가능


In [ ]:
import numpy as np

### 7.2.2 1차원 배열

배열을 고속으로 처리하는 ndarray 클래스 존재

1) **np.array()** 함수 이용

'np.array(리스트)' 로 리스트 전달하여 ndarray 생성

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

2) **np.arange()** 함수 이용

np.arange(X) 로 표기하여 일정한 간격으로 증감시킨 값의 요소를 X개 만들어줘

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

### 7.2.3 1차원 배열의 계산

ndarray의 산술 연산은 같은 위치에 있는 요소끼리 계산돼

In [ ]:
storages = np.array([1,2,3,4])
storages += storages
print(storages)

[2 4 6 8]


### 7.2.4 인덱스 참조와 슬라이스

인덱스 참조와 슬라이스는 리스트와 사용 방법 동일

슬라이스값 변경하려면 'arr[start:end]=변경하려는 값' 으로 표기

start부터 end-1까지의 리스트 작성된다는 점 주의 !!

In [ ]:
arr = np.arange(10)
arr[0:3] = 1
print(arr)

[1 1 1 3 4 5 6 7 8 9]


### 7.2.5 ndarray 사용시 주의사항

ndarray 배열을 다른 변수에 그대로 대입한 경우 해당 변수의 값을 변경하면 원래 ndarray 배열의 값도 변경돼

=> ndarray를 복사하여 두 개의 변수를 별도로 만들고 싶을 때는 **copy()** 메서드 사용

'복사할 배열.copy()'로 복사 가능

In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = arr1
arr2[0]=100

print(arr1)    # arr2 변수를 변경하면 원래 변수(arr1)도 영향받아

arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2=arr1.copy()
arr2[0]=100

print(arr1)     # arr2 변수 변경해도 원래 변수(arr1)에 영향 주지 않아

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]


### 7.2.6 view와 copy

ndarray의 슬라이스는 배열의 복사본이 아닌 view(원래 배열의 데이터) -> 원래 ndarray를 변경하게 돼

=> 슬라이스를 복사본으로 만들려면 copy()메서드 사용

### 7.2.7 부울 인덱스 참조

* 부울 인덱스 참조 : []안에 논리값(True/False) 배열 사용하여 요소 추출하는 방법

'arr[ndarray 논리값 배열]'로 표기

In [ ]:
arr = np.array([2,4,6,7])
print(arr[np.array([True,True,True,False])])
print(arr[arr%3==1])

[2 4 6]
[4 7]


### 7.2.8 범용 함수

* 범용 함수 : ndarray 배열의 각 요소에 대한 연산 결과 반환하는 함수

>* np.abs()함수 : 요소의 절댓값 반환
>* np.exp()함수 : 요소의 e의 거듭제곱 반환
>* np.sqrt()함수 : 요소의 제곱근 반환
>* np.add()함수 : 요소 간의 합 반환
>* np.subtract()함수 : 요소 간의 차이 반환
>* np.maximum()함수 : 요소 간의 최댓값 저장한 배열 반환

### 7.2.9 집합 함수

* 집합 함수 : 수학의 집합 연산 수행하는 함수

1차원 배열만을 대상으로 해 

>* np.unique()함수 : 배열 요소에서 중복을 제거하고 정렬한 결과 반환
>* np.union1d(x,y)함수 : 배열 x와 y의 합집합 정렬해서 반환
>* np.intersect1d(x,y)함수 : 배열 x와 y의 교집합 정렬해서 반환
>* np.setdiff1d(x,y)함수 : 배열 x에서 배열 y를 뺀 차집합 정렬해서 반환

### 7.2.10 난수

**np.random()** 모듈로 난수 생성

>* np.random.rand()함수 : 0 이상 1 미만의 난수 생성 / ()에 넣은 정수의 횟수만큼 난수 생성
>* np.random.randint(x,y,z)함수 : x 이상 y 미만의 정수를 z개 생성 / z에는 (2,3) 인수 넣을 수도 o
 +  from numpy.random import randint 기술해두면 randint()만으로 함수 사용 가능
>* np.random.normal()함수 : 가우스 분포를 따르는 나수 생성

## 7.3. Numpy 2차원 배열

### 7.3.1 2차원 배열

* 2차원 배열 = 행렬 => 'np.array([리스트, 리스트])'로 표기

'ndarry배열.**shape**'로 각 차원의 요소 수 반환

'ndarray배열.**reshape(a,b)**'로 지정한 인수와 같은 모양의 행렬로 변환

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)
print(arr.reshape(4,2))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 7.3.2 인덱스 참조와 슬라이스

* 인덱스 하나만 지정하면 임의의 행을 배열로 가져올 수 있다

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1])

[4 5 6]


* 개별 요소, 즉 스칼라값에 도달하려면 인덱스 두 개 지정

arr[1][2] 또는 arr[1,2]와 같이 접근

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,2])

6


In [ ]:
# 슬라이스 예
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,1:])

[5 6]


In [ ]:
# 문제
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[0,2])
print(arr[1:,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5]
 [7 8]]


### 7.3.3 axis

* axis = 좌표축

**axis=0 : 열마다 처리하는 축, axis=1 : 행마다 처리하는 축**


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [ ]:
# 문제
arr = np.array([[1,2,3],[4,5,12],[15,20,22]])
print(arr.sum(axis=1))

[ 6 21 57]


### 7.3.4 팬시 인덱스 참조

* 팬시 인덱스 참조 : 인덱스 참조로 인덱스의 배열을 이용하는 방법

ndarray 배열에서 특정 순서로 행 추출하려면 그 순서를 나타내는 배열을 인덱스 참조로 전달하면 돼

항상 원본 데이터의 복사본 반환하여 새로운 요소 작성

In [ ]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr[[3,2,0]])

[[7 8]
 [5 6]
 [1 2]]


In [ ]:
# 문제
arr = np.arange(25).reshape(5,5)
print(arr[[1,3,0]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


### 7.3.5 전치 행렬

* 전치행렬 -> 행렬의 내적 계산 등에서 사용(전치 : 행렬에서 행과 열을 바꾸는 것)

**np.transpose()** 함수 사용 or **.T** 사용

In [ ]:
arr = np.arange(10).reshape(2,5)
print(arr.T)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 7.3.6 정렬

1) **sort()** 메서드 : 2차원 배열의 경우 0을 인수로 하면 열 단위로 요소 정렬, 1을 인수로 하면 행 단위로 요소 정렬

2) **np.sort()** 함수 : 정렬된 배열의 복사본 반환

3) **argsort()**메서드 : 정렬된 배열의 인덱스 반환

In [ ]:
arr = np.array([15,30,5])
arr.argsort()

array([2, 0, 1])

In [ ]:
# 문제
arr = np.array([[8,4,2],[3,5,1]])
print(arr.argsort())
print(np.sort(arr))
arr.sort(1)
print(arr)

[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]
[[2 4 8]
 [1 3 5]]


### 7.3.7 행렬 계산

**np.dot(a,b)** : 두 행렬의 행렬곱 반환(행벡터와 열벡터의 내적을 요소로 하는 행렬 새로 생성)    -> x.dot(y) 또는 np.dot(x,y)

**np.linalg.norm(a)** : 노름 반환(벡터의 길이) <- 요소의 제곱값을 더해 루트 씌운 것

In [ ]:
# 문제
arr = np.arange(9).reshape(3,3)
print(np.dot(arr,arr))   

vec = arr.reshape(9)
print(np.linalg.norm(vec))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
14.2828568570857


### 7.3.8 통계 함수

* 통계 함수 : ndarray 배열 전체 또는 특정 축을 중심으로 수학적 처리를 수행하는 함수 또는 메서드

>* sum()메서드 : 배열의 합 반환
>* mean()메서드와 np.average()메서드 : 배열 요소의 평균 반환
>* np.max()메서드와 np.min()메서드 : 최댓값/최솟값 반환
>* np.argmax()메서드와 np.argmin()메서드 : 요소의 최댓값 또는 최솟값의 인덱스 번호 반환
>* np.std()메서드와 np.var()메서드 : 표준편차와 분산

+) sum(), mean(), argmax(), argmin() 메서드 등에서도 axis 지정해 처리 가능

열마다 처리하는 축 : axis=0 / 행마다 처리하는 축 : axis=1

In [ ]:
# 문제
arr = np.arange(15).reshape(3,5)

print(arr.mean(axis=0))
print(arr.sum(axis=1))
print(arr.min())
print(arr.argmax(axis=0))

[5. 6. 7. 8. 9.]
[10 35 60]
0
[2 2 2 2 2]


### 7.3.9 브로드캐스트

* 브로드캐스트 : 크기가 다른 numpy 배열 간의 연산에서 자동으로 처리

: 두 ndarray 연산시 크기가 작은 배열의 행과 열을 자동으로 큰 배열 쪽에 맞춰줘

: 두 배열의 행이 일치하지 않을 경우에는 행이 적은 쪽이 많은 쪽의 수에 맞추어 부족한 부분을 기존 행에서 복사(열도 마찬가지)

In [ ]:
x = np.arange(6).reshape(2,3)
print(x+1)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 문제
x = np.arange(15).reshape(3,5)
y = np.array([np.arange(5)])
z = x-y
print(z)

[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]




---



In [ ]:
# 연습문제
np.random.seed(100)
arr = np.random.randint(0,31,(5,3))
print(arr)

arr=arr.T
print(arr)

arr1=arr[:,1:4]
print(arr1)

arr1.sort(0)
print(arr1)

print(arr1.mean(axis=0))

[[ 8 24  3]
 [ 7 23 15]
 [16 10 30]
 [20  2 21]
 [ 2  2 14]]
[[ 8  7 16 20  2]
 [24 23 10  2  2]
 [ 3 15 30 21 14]]
[[ 7 16 20]
 [23 10  2]
 [15 30 21]]
[[ 7 10  2]
 [15 16 20]
 [23 30 21]]
[15.         18.66666667 14.33333333]


In [ ]:
# 종합 문제
np.random.seed(0)   # 난수 초기화

def make_image(m,n):
  image = np.random.randint(0,6,(m,n))
  return image

def change_little(matrix):
  shape = matrix.shape
  for i in range(shape[0]):
    for j in range(shape[1]):
      if np.random.randint(0,2)==1:
        matrix[i][j] = np.random.randint(0,6,1)
  return matrix

image1 = make_image(3,3)
print(image1)
print()

image2 = change_little(np.copy(image1))
print(image2)
print()

image3 = image2-image1
print(image3)
print()

image3 = np.abs(image3)

print(image3)

[[4 5 0]
 [3 3 3]
 [1 3 5]]

[[4 5 0]
 [3 3 3]
 [0 5 5]]

[[ 0  0  0]
 [ 0  0  0]
 [-1  2  0]]

[[0 0 0]
 [0 0 0]
 [1 2 0]]
